package com.customer.order.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotEmpty;
import lombok.*;

//@Entity
//@Setter
//@Getter
@Data
@DynamoDBTable(tableName = "customerdetails")
public class CustomerDetails {

    public String getName() {
        return name;
    }

  //  @NotEmpty(message = "filed is empty")
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String name;

   // private String creationDate;
    @DynamoDBAttribute
    private String phoneNumber;
@DynamoDBAttribute
    private String emailId;

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public CustomerDetails() {
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
